#!/bin/bash
# SDPRS Edge Node Provisioning Script
# 在 Raspberry Pi OS Bookworm Lite 上執行
#
# 用法: sudo ./setup_pi.sh <node_id> <server_ip>
# 範例: sudo ./setup_pi.sh glass_node_01 192.168.1.100
#
# 功能:
# 1. 系統配置 (hostname, 時區, tmpfs, watchdog)
# 2. 依賴安裝 (Python, FFmpeg, AutoSSH)
# 3. SSH 金鑰配置 (反向隧道)
# 4. 應用部署
# 5. systemd 服務安裝
# 6. 驗證

set -euo pipefail

# ===== 顏色定義 =====
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ===== 參數檢查 =====
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}錯誤: 此腳本需要以 root 權限執行${NC}"
    echo "使用: sudo $0 <node_id> <server_ip>"
    exit 1
fi

if [[ $# -lt 2 ]]; then
    echo -e "${YELLOW}用法: $0 <node_id> <server_ip>${NC}"
    echo "範例: $0 glass_node_01 192.168.1.100"
    exit 1
fi

NODE_ID="$1"
SERVER_IP="$2"

# 從 node_id 提取編號 (glass_node_01 -> 01)
NODE_NUM="${NODE_ID##*_}"
HOSTNAME="sdprs-glass-${NODE_NUM}"

# 計算隧道端口 (glass_node_01 -> 18554)
BASE_PORT=18554
TUNNEL_PORT=$((BASE_PORT + NODE_NUM - 1))

echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}SDPRS 邊緣節點佈建腳本${NC}"
echo -e "${GREEN}======================================${NC}"
echo "Node ID: ${NODE_ID}"
echo "Hostname: ${HOSTNAME}"
echo "Server IP: ${SERVER_IP}"
echo "Tunnel Port: ${TUNNEL_PORT}"
echo ""

# ===== Step 1/6: 系統配置 =====
echo -e "${GREEN}[Step 1/6] 系統配置...${NC}"

# 設定 hostname
echo "設定 hostname 為 ${HOSTNAME}..."
hostnamectl set-hostname "${HOSTNAME}"

# 更新 /etc/hosts
sed -i "s/127.0.1.1.*/127.0.1.1\t${HOSTNAME}/" /etc/hosts

# 設定時區
echo "設定時區為 Asia/Macau..."
timedatectl set-timezone Asia/Macau

# 掛載 tmpfs (保護 SD 卡)
echo "配置 tmpfs..."
if ! grep -q "tmpfs /tmp" /etc/fstab; then
    echo "tmpfs /tmp tmpfs defaults,noatime,nosuid,size=100M 0 0" >> /etc/fstab
    echo "tmpfs /var/log tmpfs defaults,noatime,nosuid,size=50M 0 0" >> /etc/fstab
    mount /tmp 2>/dev/null || true
    mount /var/log 2>/dev/null || true
fi

# 啟用硬體 watchdog
echo "啟用硬體 watchdog..."
if ! grep -q "dtparam=watchdog=on" /boot/firmware/config.txt; then
    echo "dtparam=watchdog=on" >> /boot/firmware/config.txt
fi

apt-get update
apt-get install -y watchdog

cat > /etc/watchdog.conf << EOF
max-load-1 = 24
watchdog-device = /dev/watchdog
watchdog-timeout = 15
realtime = yes
priority = 1
EOF

systemctl enable watchdog
systemctl start watchdog

# ===== Step 2/6: 依賴安裝 =====
echo -e "${GREEN}[Step 2/6] 安裝依賴...${NC}"

apt-get update
apt-get install -y \
    python3-pip python3-venv python3-pyaudio \
    ffmpeg autossh git avahi-daemon \
    libopenjp2-7 libtiff5

# 建立 sdprs 用戶
if ! id -u sdprs &>/dev/null; then
    useradd -r -m -s /bin/bash sdprs
    echo "已建立 sdprs 用戶"
fi

# 建立目錄結構
mkdir -p /opt/sdprs/edge_glass
mkdir -p /opt/sdprs/edge_glass/events
mkdir -p /opt/sdprs/edge_glass/buffer
mkdir -p /opt/mediamtx

# 建立 Python venv
echo "建立 Python 虛擬環境..."
python3 -m venv /opt/sdprs/edge_glass/venv

# 安裝 Python 依賴
echo "安裝 Python 套件..."
/opt/sdprs/edge_glass/venv/bin/pip install --upgrade pip
/opt/sdprs/edge_glass/venv/bin/pip install \
    opencv-python-headless paho-mqtt httpx pyyaml numpy psutil

# 下載 mediamtx
echo "下載 MediaMTX..."
MEDIAMTX_VERSION="v1.9.3"
if [[ ! -f /opt/mediamtx/mediamtx ]]; then
    wget -qO- "https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VERSION}/mediamtx_${MEDIAMTX_VERSION}_linux_arm64v8.tar.gz" | tar xz -C /opt/mediamtx/
    chmod +x /opt/mediamtx/mediamtx
fi

# ===== Step 3/6: SSH 金鑰配置 =====
echo -e "${GREEN}[Step 3/6] SSH 金鑰配置...${NC}"

# 生成 SSH 金鑰
if [[ ! -f /home/sdprs/.ssh/id_ed25519 ]]; then
    mkdir -p /home/sdprs/.ssh
    chmod 700 /home/sdprs/.ssh
    sudo -u sdprs ssh-keygen -t ed25519 -f /home/sdprs/.ssh/id_ed25519 -N ""
    echo "已生成 SSH 金鑰對"
fi

# 配置 SSH config
cat > /home/sdprs/.ssh/config << EOF
Host ${SERVER_IP}
    StrictHostKeyChecking no
    UserKnownKnownHostsFile /dev/null
EOF
chown sdprs:sdprs /home/sdprs/.ssh/config
chmod 600 /home/sdprs/.ssh/config

echo ""
echo -e "${YELLOW}=== 請將以下公鑰加入中央伺服器 /home/sdprs/.ssh/authorized_keys ===${NC}"
cat /home/sdprs/.ssh/id_ed25519.pub
echo -e "${YELLOW}======================================================================${NC}"
echo ""

# ===== Step 4/6: 應用部署 =====
echo -e "${GREEN}[Step 4/6] 應用部署...${NC}"

# 若有 git 可 clone，否則假設檔案已存在
if [[ -d /opt/sdprs/edge_glass/.git ]]; then
    echo "更新現有 repository..."
    cd /opt/sdprs/edge_glass && git pull
elif command -v git &>/dev/null && [[ -n "${GIT_REPO:-}" ]]; then
    echo "Clone repository..."
    git clone "${GIT_REPO}" /opt/sdprs/edge_glass
else
    echo "假設檔案已在 /opt/sdprs/edge_glass/"
fi

# 建立 config.yaml
cat > /opt/sdprs/edge_glass/config.yaml << EOF
# SDPRS Edge Node Configuration
# Auto-generated by setup_pi.sh

node_id: "${NODE_ID}"
server:
  api_url: "http://${SERVER_IP}:8000/api"
  api_key: "changeme-random-secret-key"
  mqtt_broker: "${SERVER_IP}"
  mqtt_port: 1883

camera:
  rtsp_url: "rtsp://localhost:8554/stream"
  fps: 15
  resolution: [1280, 720]

detection:
  visual:
    enabled: true
    model: "yolov8n.pt"
    confidence_threshold: 0.5
  audio:
    enabled: true
    sample_rate: 16000
    frame_duration_ms: 30
    peak_threshold_db: 35

buffer:
  pre_event_seconds: 5
  post_event_seconds: 10
  max_frames: 500

storage:
  events_dir: "./events"
  mp4_filename: "{timestamp}.mp4"

stream:
  enabled: true
  tunnel_port: ${TUNNEL_PORT}
EOF

# 建立 .env.tunnel
cat > /opt/sdprs/edge_glass/.env.tunnel << EOF
# SSH Tunnel Configuration
SERVER_HOST=${SERVER_IP}
TUNNEL_PORT=${TUNNEL_PORT}
SSH_USER=sdprs
SSH_KEY=/home/sdprs/.ssh/id_ed25519
EOF

# 設定權限
chown -R sdprs:sdprs /opt/sdprs
chmod 600 /opt/sdprs/edge_glass/.env.tunnel

# ===== Step 5/6: systemd 服務安裝 =====
echo -e "${GREEN}[Step 5/6] 安裝 systemd 服務...${NC}"

# 複製服務檔案
cp /opt/sdprs/edge_glass/systemd/sdprs-edge.service /etc/systemd/system/
cp /opt/sdprs/edge_glass/systemd/autossh-tunnel.service /etc/systemd/system/

# 重新載入 systemd
systemctl daemon-reload

# 啟用服務
systemctl enable sdprs-edge
systemctl enable autossh-tunnel

# 啟動服務
systemctl start sdprs-edge

# autossh 需要 SSH 金鑰配置後才能啟動
echo "請先配置 SSH 金鑰後執行: systemctl start autossh-tunnel"

# ===== Step 6/6: 驗證 =====
echo -e "${GREEN}[Step 6/6] 驗證...${NC}"

echo ""
echo "服務狀態:"
echo "  sdprs-edge: $(systemctl is-active sdprs-edge || echo 'inactive')"
echo "  autossh-tunnel: $(systemctl is-active autossh-tunnel || echo 'inactive')"
echo "  watchdog: $(systemctl is-active watchdog || echo 'inactive')"

echo ""
echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}佈建完成！${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo "下一步:"
echo "1. 將以下公鑰加入中央伺服器 /home/sdprs/.ssh/authorized_keys:"
echo "   $(cat /home/sdprs/.ssh/id_ed25519.pub)"
echo ""
echo "2. 啟動 SSH 隧道:"
echo "   sudo systemctl start autossh-tunnel"
echo ""
echo "3. 查看日誌:"
echo "   journalctl -u sdprs-edge -f"
echo ""